---
title: 'Lab 8: Multiple linear regression'
author: ''
output: html_document
---
	
```{r}
if(!file.exists('evals.RData')) {
	download.file("http://www.openintro.org/stat/data/evals.RData", destfile = "evals.RData")
}
load("evals.RData")
set.seed(2112) # This will ensure that the sample will return the same result each time.
```

####  Exercise 1 Is this an observational study or an experiment? The original research question posed in the paper is whether beauty leads directly to the differences in course evaluations. Given the study design, is it possible to answer this question as it is phrased? If not, rephrase the question.



#### Exercise 2 Describe the distribution of score. Is the distribution skewed? What does that tell you about how students rate courses? Is this what you expected to see? Why, or why not?



#### Exercise 3 Excluding score, select two other variables and describe their relationship using an appropriate visualization (scatterplot, side-by-side boxplots, or mosaic plot).



#### Exercise 4 Replot the scatterplot, but this time use the function jitter() on the y- or the x-coordinate. (Use ?jitter to learn more.) What was misleading about the initial scatterplot?



#### Exercise 5 Let’s see if the apparent trend in the plot is something more than natural variation. Fit a linear model called m bty to predict average professor score by average beauty rating and add the line to your plot using abline(m bty). Write out the equation for the linear model and interpret the slope. Is average beauty score a statistically significant predictor? Does it appear to be a practically significant predictor?



#### Exercise 6 Use residual plots to evaluate whether the conditions of least squares regression are reasonable. Provide plots and comments for each one (see Lab 7 for a reminder of how to make these).



#### Exercise 7 P-values and parameter estimates should only be trusted if the conditions for the regression are reasonable. Verify that the conditions for this model are reasonable using diagnostic plots.



#### Exercise 8 Is bty avg still a significant predictor of score? Has the addition of gender to the model changed the parameter estimate for bty avg?



#### Exercise 9 What is the equation of the line corresponding to males? (Hint: For males, the parameter estimate is multiplied by 1.) For two professors who received the same beauty rating, which gender tends to have the higher course evaluation score?



#### Exercise 10 Create a new model called m bty rank with gender removed and rank added in. How does R appear to handle categorical variables that have more than two levels? Note that the rank variable has three levels: teaching, tenure track, tenured.



#### Exercise 11 Which variable would you expect to have the highest p-value in this model? Why? Hint: Think about which variable would you expect to not have any association with the professor score.



#### Exercise 12 Check your suspicions from the previous exercise. Include the model output in your response.



#### Exercise 13 Interpret the coefficient associated with the ethnicity variable.



#### Exercise 14 Drop the variable with the highest p-value and re-fit the model. Did the coefficients and significance of the other explanatory variables change? (One of the things that makes multiple regression interesting is that coefficient estimates depend on the other variables that are included in the model.) If not, what does this say about whether or not the dropped variable was collinear with the other explanatory variables?



#### Exercise 15 Using backward-selection and p-value as the selection criterion, determine the best model. You do not need to show all steps in your answer, just the output for the final model. Also, write out the linear model for predicting score based on the final model you settle on.



#### Exercise 16 Verify that the conditions for this model are reasonable using diagnostic plots.



#### Exercise 17 The original paper describes how these data were gathered by taking a sample of professors from the University of Texas at Austin and including all courses that they have taught. Considering that each row represents a course, could this new information have an impact on any of the conditions of linear regression?



#### Exercise 18 Based on your final model, describe the characteristics of a professor and course at University of Texas at Austin that would be associated with a high evaluation score.



#### Exercise 19 Would you be comfortable generalizing your conclusions to apply to professors generally (at any university)? Why or why not?
